default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: "https://github.com/psf/black"
    rev: "22.10.0"
    hooks:
      - id: black
        stages: [commit]

  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: "v2.7.1"
    hooks:
      - id: prettier
        stages: [commit]
        exclude: tests\/test_build\/.+\.html$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.252"
    hooks:
      - id: ruff
        stages: [commit]

  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: v2.18.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
